version: 2

jobs:
  build:
    working_directory: ~/django_ecommerce
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_IGNORE_VIRTUALENVS: True
          PIPENV_VENV_IN_PROJECT: True
          PIPENV_DONT_LOAD_ENV: 0
    steps:
      - checkout
      - run:
          command: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          command: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore-cache:
          keys:
            - v1-pipenv-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - v1-pipenv-cache-{{ .Branch }}
            - v1-pipenv-cache-
      - run:
          name: Installing packages
          command: pipenv install --dev
      - run:
          command: cp django_ecommerce/settings/local.py.example django_ecommerce/settings/local.py
      - run:
          command: cp .env.example .env
      - run:
          command: pipenv run python manage.py makemigrations
      - run:
          command: pipenv run python manage.py migrate
      - save_cache:
          key: pipenv-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
      - run:
          command: pipenv run python manage.py test
      - run:
          command: pipenv run python manage.py check --deploy
          environment:
            DJANGO_SETTINGS_MODULE: 'django_ecommerce.settings.production'
            SECRET_KEY: $SECRET_KEY
            ALLOWED_HOSTS: '.example.org'
            DATABASE_URL: 'sqlite:///'
  deploy:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
